
var miniRumbleFont = [
    "fonts/miniRumble_font/_colon.png",
    "fonts/miniRumble_font/_comma.png",
    "fonts/miniRumble_font/_dot.png",
    "fonts/miniRumble_font/_e_mark.png",
    "fonts/miniRumble_font/_q_mark.png",
    "fonts/miniRumble_font/_s_colon.png",
    "fonts/miniRumble_font/_0.png",
    "fonts/miniRumble_font/_1.png",
    "fonts/miniRumble_font/_2.png",
    "fonts/miniRumble_font/_3.png",
    "fonts/miniRumble_font/_4.png",
    "fonts/miniRumble_font/_5.png",
    "fonts/miniRumble_font/_6.png",
    "fonts/miniRumble_font/_7.png",
    "fonts/miniRumble_font/_8.png",
    "fonts/miniRumble_font/_9.png",
    "fonts/miniRumble_font/a.png",
    "fonts/miniRumble_font/b.png",
    "fonts/miniRumble_font/c.png",
    "fonts/miniRumble_font/d.png",
    "fonts/miniRumble_font/e.png",
    "fonts/miniRumble_font/f.png",
    "fonts/miniRumble_font/g.png",
    "fonts/miniRumble_font/h.png",
    "fonts/miniRumble_font/i.png",
    "fonts/miniRumble_font/j.png",
    "fonts/miniRumble_font/k.png",
    "fonts/miniRumble_font/l.png",
    "fonts/miniRumble_font/m.png",
    "fonts/miniRumble_font/n.png",
    "fonts/miniRumble_font/o.png",
    "fonts/miniRumble_font/p.png",
    "fonts/miniRumble_font/q.png",
    "fonts/miniRumble_font/r.png",
    "fonts/miniRumble_font/s.png",
    "fonts/miniRumble_font/t.png",
    "fonts/miniRumble_font/u.png",
    "fonts/miniRumble_font/v.png",
    "fonts/miniRumble_font/w.png",
    "fonts/miniRumble_font/x.png",
    "fonts/miniRumble_font/y.png",
    "fonts/miniRumble_font/z.png"
];

miniRumbleFont.forEach(font => {importTexture(font)});